/* REACT Roadmap
1. Learn JavaScript fundamentals
2. Understand ES6+ features (arrow functions, destructuring, modules, etc.)
3. Learn HTML and CSS basics
4. Get familiar with Node.js and npm
5. Learn React basics (components, JSX, props, state)
6. Understand React component lifecycle
7. Learn about React hooks (useState, useEffect, etc.)
8. Explore React Router for navigation
9. Learn state management (Context API, Redux)
10. Understand testing in React (Jest, React Testing Library)
11. Learn about performance optimization in React
12. Explore server-side rendering (Next.js)
13. Build and deploy React applications
14. Stay updated with the latest React features and best practices
15. Join React communities and contribute to open-source projects
*/

// How to install and use React 18 in your project
// 1. Make sure you have Node.js installed on your machine.
// 2. Create a new React project using Create React App by running the following command in your terminal:
//    npx create-react-app my-app

// 3. Navigate to the project directory:
//    cd my-app

// 4. Install React 18 and ReactDOM 18 (if not already installed) by running:
//    npm install react@18 react-dom@18

// 5. Replace the contents of src/index.js with the following code:
// src/index.js

// 6. Start the development server to see your React application in action:
//    npm start

// Now, here is the code for src/index.js:

import React from 'react'
import ReactDOM from 'react-dom/client'


function Basic() {
    return(
        <>
            <h2>This is Basic concepts in React</h2>
            <h1>This is h1 tag</h1>
        </>
    )
}   
const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
    <>
        <Basic />
    </>
);
export default Basic;




/*
explanation of folder structures in react project:
firts node_modules folder contains all the dependencies and packages required for the project to run.
   -> It is automatically created when you run npm install.
   -> every package listed in package.json is installed in this folder.
public folder contains static files like index.html, images, etc.
   -> The index.html file is the main HTML file that loads the React application.
   -> Other files in this folder can be accessed directly via URL.
src folder contains all the source code of the React application including components, styles, and other assets.
   -> This is where you will spend most of your time writing code.
   -> The main entry point of the application is usually src/index.js.
   -> You can create additional folders inside src for better organization (e.g., components, styles, utils).
.gitignore file specifies which files and directories should be ignored by Git version control.
   -> Commonly ignored files include node_modules, build artifacts, and environment variable files.
package.json file contains metadata about the project and lists dependencies and scripts.
   -> It is used by npm to manage the project's packages.
   -> You can define scripts for building, testing, and starting the application here.
package-lock.json file is automatically generated by npm to lock the versions of installed packages.
   -> It ensures that the same package versions are used when the project is installed on different machines.
README.md file contains information about the project and instructions for developers.
    -> It is a good place to document how to set up and run the project. 

*/

// How to render basic code in react without using JSX
// 1. In React, you can create elements using the React.createElement() method.
// 2. This method takes three arguments: the type of element, an object of props, and the children of the element.
// 3. You can then render this element to the DOM using ReactDOM.createRoot() and the render() method.
// Example code is provided above in src/index.js.

// Note: JSX is a syntax extension for JavaScript that allows you to write HTML-like code in your JavaScript files.
// It is transpiled to React.createElement() calls by tools like Babel.
// However, using React.createElement() directly is a way to understand how React works under the hood.

// basic code without JSX is already provided above in src/index.js.
/*import React from 'react'
import ReactDOM from 'react-dom/client'

let h2 = React.createElement('h2', {}, "this is h2 tag")
let root2 = ReactDOM.createRoot(document.getElementById('root'));

root2.render(h2)


// how to render h1 and h2 both together without using JSX
let h1 = React.createElement('h1', {}, "this is h1 tag")

let container = React.createElement('div', {}, [h1, h2]);

let root = ReactDOM.createRoot(document.getElementById('root'));

root.render(container);

function test(){
}
export default test */

// basic code of jsx
/*
import React from 'react'
import ReactDOM from 'react-dom/client'

let h1 = <h1>this is h1 tag</h1>

let root = ReactDOM.createRoot(document.getElementById('root'));

root.render(h1)

function test(){
}
export default test
*/

// what is the difference between React and ReactDOM?
// React is a JavaScript library for building user interfaces, while ReactDOM is a package that provides DOM-specific methods for rendering React components to the DOM.
// In other words, React is responsible for creating components and managing their state and lifecycle, while ReactDOM is responsible for rendering those components to the web page.
// React can be used for building components that can be rendered in different environments (like mobile apps with React Native), whereas ReactDOM is specifically for web applications.
// ReactDOM provides methods like createRoot() and render() to mount React components to the DOM.

// how to create multiple elements without using JSX in react?
// You can create multiple elements without using JSX in React by using the React.createElement() method to create each element and then combining them into a parent element.
// You can use an array to hold multiple child elements and pass that array as the third argument to React.createElement() for the parent element.
// Example code:
/*
import React from 'react'
import ReactDOM from 'react-dom/client'

let h1 = React.createElement('h1', {}, "this is h1 tag")
let h2 = React.createElement('h2', {}, "this is h2 tag")

let container = React.createElement('div', {}, [h1, h2]);

let root = ReactDOM.createRoot(document.getElementById('root'));

root.render(container)

function test(){
}
export default test
*/
